server:
  persistentVolume:
    enabled: true
    size: 8Gi

  service:
    type: ClusterIP

  extraScrapeConfigs:
    - job_name: "voting-backend"
      metrics_path: /actuator/prometheus
      static_configs:
        - targets:
            - voting-backend.polling-app.svc.cluster.local:8080

alertmanager:
  enabled: false

pushgateway:
  enabled: false
