apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: polling-app
resources:
  - namespace.yml
  - mysql-secret.yml
  - mysql-deployment.yml
  - mysql-service.yml
  - backend-deployment.yml
  - backend-service.yml
  - frontend-deployment.yml
  - frontend-service.yml
  - ingress.yml
images:
  - name: voting-backend
    newName: 140311410153.dkr.ecr.ap-south-1.amazonaws.com/polling-backend
    newTag: latest
  - name: voting-frontend
    newName: 140311410153.dkr.ecr.ap-south-1.amazonaws.com/polling-frontend
    newTag: latest
