apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: polling-app
  namespace: argocd
spec:
  project: polling
  source:
    repoURL: https://github.com/Harsha2318/polling-devops.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: polling-app
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

